<?php
return array (
    'windows nt 6.2'    => 'Windows 8',
    'windows nt 6.1'    => 'Windows 7',
    'windows nt 6.0'    => 'Windows Vista',
    'windows nt 5.2'    => 'Windows 2003',
    'windows nt 5.0'    => 'Windows 2000',
    'windows nt 5.1'    => 'Windows XP',
    'windows nt 4.0'    => 'Windows NT 4.0',
    'winnt4.0'          => 'Windows NT 4.0',
    'winnt 4.0'         => 'Windows NT',
    'winnt'             => 'Windows NT',
    'windows 98'        => 'Windows 98',
    'win98'             => 'Windows 98',
    'windows 95'        => 'Windows 95',
    'win95'             => 'Windows 95',
    'windows'           => 'Windows',
    'os x'              => 'Mac OS X',
    'ppc mac'           => 'Power PC Mac',
    'freebsd'           => 'FreeBSD',
    'ppc'               => 'Macintosh',
    'ubuntu'            => 'Ubuntu',
    'debian'            => 'Debian',
    'linux'             => 'Linux',
    'sunos'             => 'Sun Solaris',
    'beos'              => 'BeOS',
    'apachebench'       => 'ApacheBench',
    'aix'               => 'AIX',
    'irix'              => 'Irix',
    'osf'               => 'DEC OSF',
    'hp-ux'             => 'HP-UX',
    'netbsd'            => 'NetBSD',
    'bsdi'              => 'BSDi',
    'openbsd'           => 'OpenBSD',
    'gnu'               => 'GNU/Linux',
    'unix'              => 'Unknown Unix OS',
    
    'symbian'           => "Symbian",
    'SymbianOS'         => "SymbianOS",
    'elaine'            => "Palm",
    'palm'              => "Palm",
    'series60'          => "Symbian S60",
    'windows ce'        => "Windows CE",
);
?>
