function searchAuto(){var b=0<$("#search-field").length?$("#search-field")[0].value.toLowerCase():"";if(0<b.length){var a=new Map;-1!==window.location.hostname.indexOf("www.caixabank.es")&&(a.set("hipoteca","https://www.caixabank.es/particular/hipotecas/simulador-calcular-hipoteca.html"),a.set("préstamo","https://www.caixabank.es/particular/prestamos-personales/prestamos.html"));$(".mic-button").attr("src","https://www.caixabank.es/deployedfiles/common/R2016/Estaticos/images/gif/loadT.gif");$(".mic-button").css("right",
"12px");$(".mic-button").css("width","21px");var c;c=JSON.parse('{"event_category":"buscador por voz","event_action":"clic en boton","event_label":"Microphone","page_internal_search_kw":""}');c.page_internal_search_kw=b;"function"===typeof callUtagLink&&callUtagLink(c);setTimeout(function(){0<b.length&&(a.has(b)?("undefined"!==typeof funcPresearch&&"undefined"!==typeof funcPresearch.registerNewSearchKey&&funcPresearch.registerNewSearchKey(b),window.location.replace(a.get(b))):(0<$("#prebuscadorCabecera").find("form").length&&
$("#prebuscadorCabecera").find("form").submit(),0<$("#prebuscadorEMPCabecera").find("form").length&&$("#prebuscadorEMPCabecera").find("form").submit()))},3E3)}}
function MediaStreamRecorder(b){if(!b)throw"MediaStream is mandatory.";var a;this.start=function(c){var d;"undefined"!=typeof MediaRecorder?d=MediaRecorderWrapper:(IsChrome||IsOpera||IsEdge)&&(-1!==this.mimeType.indexOf("video")?d=WhammyRecorder:-1!==this.mimeType.indexOf("audio")&&(d=StereoAudioRecorder));"image/gif"===this.mimeType&&(d=GifRecorder);"audio/wav"!==this.mimeType&&"audio/pcm"!==this.mimeType||(d=StereoAudioRecorder);this.recorderType&&(d=this.recorderType);(a=new d(b)).blobs=[];var f=
this;a.ondataavailable=function(b){a.blobs.push(b);f.ondataavailable(b)};a.onstop=this.onstop;a.onStartedDrawingNonBlankFrames=this.onStartedDrawingNonBlankFrames;(a=mergeProps(a,this)).start(c)};this.onStartedDrawingNonBlankFrames=function(){};this.clearOldRecordedFrames=function(){a&&a.clearOldRecordedFrames()};this.stop=function(){a&&a.stop()};this.ondataavailable=function(a){this.disableLogs||console.log("ondataavailable..",a)};this.onstop=function(a){console.warn("stopped..",a)};this.save=function(b,
d){b?invokeSaveAsDialog(b,d):a&&ConcatenateBlobs(a.blobs,a.blobs[0].type,function(a){invokeSaveAsDialog(a)})};this.pause=function(){a&&(a.pause(),this.disableLogs||console.log("Paused recording.",this.mimeType||a.mimeType))};this.resume=function(){a&&(a.resume(),this.disableLogs||console.log("Resumed recording.",this.mimeType||a.mimeType))};this.recorderType=null;this.mimeType="video/webm";this.disableLogs=!1}
function MultiStreamRecorder(b,a){(b=b||[])instanceof MediaStream&&(b=[b]);var c,d,f=this;(a=a||{mimeType:"video/webm",video:{width:360,height:240}}).frameInterval||(a.frameInterval=10);a.video||(a.video={});a.video.width||(a.video.width=360);a.video.height||(a.video.height=240);this.start=function(k){for(var h in c=new MultiStreamsMixer(b),g=[],b.forEach(function(a){a.getVideoTracks().forEach(function(a){g.push(a)})}),g.length&&(c.frameInterval=a.frameInterval||10,c.width=a.video.width||360,c.height=
a.video.height||240,c.startDrawingFrames()),"function"==typeof f.previewStream&&f.previewStream(c.getMixedStream()),d=new MediaStreamRecorder(c.getMixedStream()),f)"function"!=typeof f[h]&&(d[h]=f[h]);var g;d.ondataavailable=function(a){f.ondataavailable(a)};d.onstop=f.onstop;d.start(k)};this.stop=function(a){d&&d.stop(function(b){a(b)})};this.pause=function(){d&&d.pause()};this.resume=function(){d&&d.resume()};this.clearRecordedData=function(){d&&(d.clearRecordedData(),d=null);c&&(c.releaseStreams(),
c=null)};this.addStreams=this.addStream=function(a){if(!a)throw"First parameter is required.";a instanceof Array||(a=[a]);b.concat(a);d&&c&&c.appendStreams(a)};this.resetVideoStreams=function(a){c&&(!a||a instanceof Array||(a=[a]),c.resetVideoStreams(a))};this.ondataavailable=function(a){f.disableLogs||console.log("ondataavailable",a)};this.onstop=function(){};this.name="MultiStreamRecorder";this.toString=function(){return this.name}}
function MultiStreamsMixer(b){function a(){var b,p,d;h||(b=k.length,p=!1,d=[],k.forEach(function(a){a.stream||(a.stream={});a.stream.fullcanvas?p=a:d.push(a)}),p?(g.width=p.stream.width,g.height=p.stream.height):d.length?(g.width=1<b?2*d[0].width:d[0].width,g.height=2<b?2*d[0].height:d[0].height):(g.width=e.width||360,g.height=e.height||240),p&&p instanceof HTMLVideoElement&&c(p),d.forEach(function(a,b){c(a,b)}),setTimeout(a,e.frameInterval))}function c(a,b){var e,c,k,d;h||(c=e=0,k=a.width,d=a.height,
1===b&&(e=a.width),2===b&&(c=a.height),3===b&&(e=a.width,c=a.height),void 0!==a.stream.left&&(e=a.stream.left),void 0!==a.stream.top&&(c=a.stream.top),void 0!==a.stream.width&&(k=a.stream.width),void 0!==a.stream.height&&(d=a.stream.height),l.drawImage(a,e,c,k,d),"function"==typeof a.stream.onRender&&a.stream.onRender(l,e,c,k,d,b))}function d(a){var b=document.createElement("video");return"srcObject"in b?b.srcObject=a:b.src=r.createObjectURL(a),b.muted=!0,b.volume=0,b.width=a.width||e.width||360,
b.height=a.height||e.height||240,b.play(),b}function f(a){k=[];(a=a||b).forEach(function(a){var b;a.getVideoTracks().length&&((b=d(a)).stream=a,k.push(b))})}var k=[],h=!1,g=document.createElement("canvas"),l=g.getContext("2d");g.style="opacity:0;position:absolute;z-index:-1;top: -100000000;left:-1000000000; margin-top:-1000000000;margin-left:-1000000000;";(document.body||document.documentElement).appendChild(g);this.disableLogs=!1;this.frameInterval=10;this.width=360;this.height=240;this.useGainNode=
!0;var e=this,q=window.AudioContext;void 0===q&&("undefined"!=typeof webkitAudioContext&&(q=webkitAudioContext),"undefined"!=typeof mozAudioContext&&(q=mozAudioContext));var r=window.URL;void 0===r&&"undefined"!=typeof webkitURL&&(r=webkitURL);"undefined"!=typeof navigator&&void 0===navigator.getUserMedia&&(void 0!==navigator.webkitGetUserMedia&&(navigator.getUserMedia=navigator.webkitGetUserMedia),void 0!==navigator.mozGetUserMedia&&(navigator.getUserMedia=navigator.mozGetUserMedia));var m=window.MediaStream;
void 0===m&&"undefined"!=typeof webkitMediaStream&&(m=webkitMediaStream);void 0!==m&&("getVideoTracks"in m.prototype||(m.prototype.getVideoTracks=function(){if(!this.getTracks)return[];var a=[];return this.getTracks.forEach(function(b){-1!==b.kind.toString().indexOf("video")&&a.push(b)}),a},m.prototype.getAudioTracks=function(){if(!this.getTracks)return[];var a=[];return this.getTracks.forEach(function(b){-1!==b.kind.toString().indexOf("audio")&&a.push(b)}),a}),void 0===m.prototype.stop&&(m.prototype.stop=
function(){this.getTracks().forEach(function(a){a.stop()})}));var n={};void 0!==q?n.AudioContext=q:"undefined"!=typeof webkitAudioContext&&(n.AudioContext=webkitAudioContext);this.startDrawingFrames=function(){a()};this.appendStreams=function(a){if(!a)throw"First parameter is required.";a instanceof Array||(a=[a]);b.concat(a);a.forEach(function(a){var b;a.getVideoTracks().length&&((b=d(a)).stream=a,k.push(b));a.getAudioTracks().length&&e.audioContext&&((a=e.audioContext.createMediaStreamSource(a)).connect(e.audioDestination),
e.audioSources.push(a))})};this.releaseStreams=function(){k=[];h=!0;e.gainNode&&(e.gainNode.disconnect(),e.gainNode=null);e.audioSources.length&&(e.audioSources.forEach(function(a){a.disconnect()}),e.audioSources=[]);e.audioDestination&&(e.audioDestination.disconnect(),e.audioDestination=null);e.audioContext=null;l.clearRect(0,0,g.width,g.height);g.stream&&(g.stream.stop(),g.stream=null)};this.resetVideoStreams=function(a){!a||a instanceof Array||(a=[a]);f(a)};this.name="MultiStreamsMixer";this.toString=
function(){return this.name};this.getMixedStream=function(){h=!1;var a=function(){var a;f();"captureStream"in g?a=g.captureStream():"mozCaptureStream"in g?a=g.mozCaptureStream():e.disableLogs||console.error("Upgrade to latest Chrome or otherwise enable this flag: chrome://flags/#enable-experimental-web-platform-features");var b=new m;return a.getVideoTracks().forEach(function(a){b.addTrack(a)}),g.stream=b}(),c=function(){n.AudioContextConstructor||(n.AudioContextConstructor=new n.AudioContext);e.audioContext=
n.AudioContextConstructor;e.audioSources=[];!0===e.useGainNode&&(e.gainNode=e.audioContext.createGain(),e.gainNode.connect(e.audioContext.destination),e.gainNode.gain.value=0);var a=0;return b.forEach(function(b){b.getAudioTracks().length&&(a++,b=e.audioContext.createMediaStreamSource(b),!0===e.useGainNode&&b.connect(e.gainNode),e.audioSources.push(b))}),a?(e.audioDestination=e.audioContext.createMediaStreamDestination(),e.audioSources.forEach(function(a){a.connect(e.audioDestination)}),e.audioDestination.stream):
void 0}();return c&&c.getAudioTracks().forEach(function(b){a.addTrack(b)}),b.forEach(function(a){a.fullcanvas}),a}}
(function(){var b,a,c,d,f;b=jQuery;a=window;document;d={language:"en-US",APIKey:null,autoStopTime:5E3,recognitionContinuous:!(c="af-ZA am-ET hy-AM az-AZ id-ID ms-MY bn-BD bn-IN ca-ES cs-CZ da-DK de-DE en-US en-AU en-CA en-GH en-GB en-IN en-IE en-KE en-NZ en-NG en-PH en-SG en-ZA en-TZ es-ES es-AR es-BO es-CL es-CO es-CR es-EC es-SV es-US es-GT es-HN es-MX es-NI es-PA es-PY es-PE es-PR es-DO es-UY es-VE eu-ES fil-PH fr-FR fr-CA gl-ES ka-GE gu-IN hr-HR zu-ZA is-IS it-IT jv-ID kn-IN km-KH lo-LA lv-LV lt-LT hu-HU ml-IN mr-IN nl-NL ne-NP nb-NO pl-PL pt-PT pt-BR ro-RO si-LK sk-SK sl-SI su-ID sw-TZ sw-KE fi-FI sv-SE ta-IN ta-SG ta-LK ta-MY te-IN vi-VN tr-TR ur-PK ur-IN el-GR bg-BG ru-RU sr-RS uk-UA he-IL ar-IL ar-JO ar-AE ar-BH ar-DZ ar-SA ar-IQ ar-KW ar-MA ar-TN ar-OM ar-PS ar-QA ar-LB ar-EG fa-IR hi-IN th-TH ko-KR yue-Hant-HK ja-JP zh-HK zh-TW zh".split(" ")),tooltip:!0,
iconClass:null,imgSrc:"/deployedfiles/common/R2016/Estaticos/images/svg/micro.svg"};f=function(a,c){this.element=a;c&&c.language&&((a=this._isSupportedLanguage(c.language))?c.language=a:(delete c.language,console.log("Used default language")));this.options=b.extend(!0,{},d,c);this._defaults=d;this._name="speechjs";this._init()};b.extend(f.prototype,{_init:function(){var c,d,g,f,e=this,q=b(this.element);void 0!==e.options.iconClass&&null!==e.options.iconClass&&""!==e.options.iconClass?c=b('\x3cdiv class\x3d"'+
e.options.iconClass+'"\x3e\x3c/div\x3e'):void 0!==e.options.imgSrc&&null!==e.options.imgSrc&&""!==e.options.imgSrc&&(c=b('\x3cimg class\x3d"mic-button" src\x3d"'+e.options.imgSrc+'"/\x3e'));this.data=b.data(this);b.data(this,"micButton",c);(d=/edg(e)?/.test(navigator.userAgent.toLowerCase())?void 0:a.SpeechRecognition||a.webkitSpeechRecognition)?(g=new d,b.data(this,"recognition",g)):(console.log("Sorry, Your Browser Doesn't Support the Web Speech API."),e.options.APIKey&&(f=this._getUserMedia(),
b.data(this,"mediaRecorder",null),b.data(this,"streamReference",null),f?b.data(this,"getUserMedia",f):console.log("Sorry, Your Browser Doesn't Support the getUserMedia.")));null!==c&&(g||f)&&(q.addClass("textbox-with-mic"),(d=b('\x3cdiv class\x3d"content-mic-button"\x3e\x3c/div\x3e')).insertBefore(q),q.appendTo(d),c.appendTo(d),g?e._voiceRecognition():f&&e.options.tooltip&&(d.addClass("mic-tooltip"),b('\x3cdiv class\x3d"mic-tooltip-bottom"\x3e\x3cspan\x3eClick to Stop.\x3c/span\x3e\x3ci\x3e\x3c/i\x3e\x3c/div\x3e').appendTo(d)),
c.on("click",function(a){e._clickMic(a)}))},_clickMic:function(a){var c=this;return this.data=b.data(this),this.data.micButton.hasClass("active")?(this.data.micButton.removeClass("active"),this.data.micButton.next("[class*\x3d'mic-tooltip-']").removeClass("show"),this.data.recognition?this.data.recognition.stop():this.data.getUserMedia&&this._stopUserMedia()):(this.data.micButton.addClass("active"),this.data.micButton.next("[class*\x3d'mic-tooltip-']").addClass("show"),this.data.recognition?this.data.recognition.start():
this.data.getUserMedia&&navigator.mediaDevices.getUserMedia({audio:!0}).then(function(a){c._onUserMediaSuccess(a)}).catch(function(a){c._onUserMediaError(a)})),a.stopPropagation()},_voiceRecognition:function(){var a=this,c=b(this.element),d="";this.data=b.data(this);this.data.recognition.continuous=this.options.recognitionContinuous;this.data.recognition.lang=this.options.language;this.data.recognition.onstart=function(){console.log("Voice recognition activated. Try speaking into the microphone.");
d="";c.val(d).focus()};this.data.recognition.onspeechend=function(){console.log("You were quiet for a while so voice recognition turned itself off.");a.data.micButton.removeClass("active")};this.data.recognition.onresult=function(b){var e=b.resultIndex,k=b.results[e][0].transcript;1==e&&k==b.results[0][0].transcript||(d+=k,c.val(a._capitalize(d)));searchAuto()};this.data.recognition.onerror=function(b){a.data.micButton&&a.data.micButton.removeClass("active");"no-speech"==b.error&&console.log("No speech was detected. Try again.")}},
_getUserMedia:function(){function a(a,c,d){var e=b;return e?new Promise(function(b,c){e.call(navigator,a,b,c)}):Promise.reject(Error("getUserMedia is not implemented in this browser"))}var b=navigator.getUserMedia||navigator.webkitGetUserMedia||navigator.mozGetUserMedia||navigator.msGetUserMedia;return void 0===navigator.mediaDevices&&(navigator.mediaDevices={}),void 0===navigator.mediaDevices.getUserMedia&&(navigator.mediaDevices.getUserMedia=a),navigator.mediaDevices.getUserMedia!==a||!!b},_onUserMediaSuccess:function(a){var c=
this;b(this.element);this.data=b.data(this);this.data.streamReference=a;this.data.mediaRecorder=new MediaStreamRecorder(a);this.data.mediaRecorder.mimeType="audio/wav";this.data.mediaRecorder.audioChannels=1;this.data.mediaRecorder.ondataavailable=function(a){var d=URL.createObjectURL(a);b(".jumbotron \x3e .container").append('\x3cbr\x3e\x3caudio controls src\x3d"'+d+'"\x3e\x3c/audio\x3e \x3ca href\x3d"'+d+'" target\x3d"_blank"\x3e'+d+"\x3c/a\x3e");c._sendCloudSpeechToText(a)};this.data.mediaRecorder.start(25E6);
this.data.autoStop=setTimeout(function(){c.data.micButton.trigger("click")},this.options.autoStopTime)},_onUserMediaError:function(a){console.log("Error capturing audio.")},_stopUserMedia:function(){this.data=b.data(this);this.data.autoStop&&clearTimeout(this.data.autoStop);this.data.mediaRecorder&&this.data.mediaRecorder.stop();this.data.streamReference&&(this.data.streamReference.getAudioTracks().forEach(function(a){a.stop()}),this.data.streamReference.getVideoTracks().forEach(function(a){a.stop()}),
this.data.streamReference=null)},_sendCloudSpeechToText:function(a){var c,d=this,f=b(this.element);this.data=b.data(this);(c=new FileReader).readAsDataURL(a);c.onloadend=function(){var a=c.result,a={audio:{content:a=a.substr(a.indexOf(",")+1)},config:{encoding:"LINEAR16",languageCode:d.options.language}};b.ajax({url:"https://speech.googleapis.com/v1/speech:recognize?alt\x3djson\x26key\x3d"+d.options.APIKey,method:"POST",dataType:"json",contentType:"application/json",data:JSON.stringify(a),success:function(a){a.results&&
a.results[0].alternatives&&f.val(d._capitalize(a.results[0].alternatives[0].transcript));searchAuto()},error:function(a){console.log("Error sending audio.")}})}},_capitalize:function(a){return a.length?a[0].toUpperCase()+a.slice(1):a},_isSupportedLanguage:function(a){var d;return a&&(d=b.grep(c,function(b){return b.toLowerCase()===a.toLowerCase()})[0]||b.grep(c,function(b){return b.toLowerCase()===a.toLowerCase()+"-"+a.toLowerCase()})[0]||b.grep(c,function(b){return 0===b.toLowerCase().indexOf(a.toLowerCase())})[0]),
d||console.log('Language not supported: "'+a+'"'),d},updateLanguage:function(a){this.data=b.data(this);(a=this._isSupportedLanguage(a))&&(this.data.recognition&&(this.data.recognition.lang=a),this.options.language=a)}});b.fn.speechjs=function(){var a=arguments[0],c=Array.prototype.slice.call(arguments,1);return this instanceof b||b.extend(d,a),this.each(function(){var d=b.data(this,"plugin_speechjs");if(!d)return b.data(this,"plugin_speechjs",new f(this,a));"object"!=typeof a&&void 0!==a&&(d[a]?d[a].apply(d,
c):console.log("Method "+a+" does not exist on Plugin"))})}}).call(this);void 0!==MediaStreamRecorder&&(MediaStreamRecorder.MultiStreamRecorder=MultiStreamRecorder);var AudioContext,browserFakeUserAgent="Fake/5.0 (FakeOS) AppleWebKit/123 (KHTML, like Gecko) Fake/12.3.4567.89 Fake/123.45";
!function(b){"undefined"==typeof window&&("undefined"==typeof window&&"undefined"!=typeof global&&(global.navigator={userAgent:browserFakeUserAgent,getUserMedia:function(){}},b.window=global),"undefined"==typeof document&&(b.document={},document.createElement=document.captureStream=document.mozCaptureStream=function(){return{}}),"undefined"==typeof location&&(b.location={protocol:"file:",href:"",hash:""}),"undefined"==typeof screen&&(b.screen={width:0,height:0}))}("undefined"!=typeof global?global:
window);void 0===(AudioContext=window.AudioContext)&&("undefined"!=typeof webkitAudioContext&&(AudioContext=webkitAudioContext),"undefined"!=typeof mozAudioContext&&(AudioContext=mozAudioContext));"undefined"==typeof window&&(window={});void 0===(AudioContext=window.AudioContext)&&("undefined"!=typeof webkitAudioContext&&(AudioContext=webkitAudioContext),"undefined"!=typeof mozAudioContext&&(AudioContext=mozAudioContext));var URL=window.URL;void 0===URL&&"undefined"!=typeof webkitURL&&(URL=webkitURL);
"undefined"!=typeof navigator?(void 0!==navigator.webkitGetUserMedia&&(navigator.getUserMedia=navigator.webkitGetUserMedia),void 0!==navigator.mozGetUserMedia&&(navigator.getUserMedia=navigator.mozGetUserMedia)):navigator={getUserMedia:function(){},userAgent:browserFakeUserAgent};var IsEdge=!(-1===navigator.userAgent.indexOf("Edge")||!navigator.msSaveBlob&&!navigator.msSaveOrOpenBlob),IsOpera=!1;"undefined"!=typeof opera&&navigator.userAgent&&-1!==navigator.userAgent.indexOf("OPR/")&&(IsOpera=!0);
var IsChrome=!IsEdge&&!IsEdge&&!!navigator.webkitGetUserMedia,MediaStream=window.MediaStream;function mergeProps(b,a){for(var c in a)"function"!=typeof a[c]&&(b[c]=a[c]);return b}function dropFirstFrame(b){return b.shift(),b}
function invokeSaveAsDialog(b,a){if(!b)throw"Blob object is required.";if(!b.type)try{b.type="video/webm"}catch(k){}var c,d=(b.type||"video/webm").split("/")[1];a&&-1!==a.indexOf(".")&&(a=(c=a.split("."))[0],d=c[1]);d=(a||Math.round(9999999999*Math.random())+888888888)+"."+d;if(void 0!==navigator.msSaveOrOpenBlob)return navigator.msSaveOrOpenBlob(b,d);if(void 0!==navigator.msSaveBlob)return navigator.msSaveBlob(b,d);var f=document.createElement("a");f.href=URL.createObjectURL(b);f.target="_blank";
f.download=d;navigator.mozGetUserMedia&&(f.onclick=function(){(document.body||document.documentElement).removeChild(f)},(document.body||document.documentElement).appendChild(f));d=new MouseEvent("click",{view:window,bubbles:!0,cancelable:!0});f.dispatchEvent(d);navigator.mozGetUserMedia||URL.revokeObjectURL(f.href)}
function bytesToSize(b){if(0===b)return"0 Bytes";var a=parseInt(Math.floor(Math.log(b)/Math.log(1E3)),10);return(b/Math.pow(1E3,a)).toPrecision(3)+" "+["Bytes","KB","MB","GB","TB"][a]}void 0===MediaStream&&"undefined"!=typeof webkitMediaStream&&(MediaStream=webkitMediaStream);
void 0!==MediaStream&&("getVideoTracks"in MediaStream.prototype||(MediaStream.prototype.getVideoTracks=function(){if(!this.getTracks)return[];var b=[];return this.getTracks.forEach(function(a){-1!==a.kind.toString().indexOf("video")&&b.push(a)}),b},MediaStream.prototype.getAudioTracks=function(){if(!this.getTracks)return[];var b=[];return this.getTracks.forEach(function(a){-1!==a.kind.toString().indexOf("audio")&&b.push(a)}),b}),"stop"in MediaStream.prototype||(MediaStream.prototype.stop=function(){this.getAudioTracks().forEach(function(b){b.stop&&
b.stop()});this.getVideoTracks().forEach(function(b){b.stop&&b.stop()})}));"undefined"!=typeof location&&0===location.href.indexOf("file:")&&console.error("Please load this HTML file on HTTP or HTTPS.");var ObjectStore={AudioContext:AudioContext};
function isMediaRecorderCompatible(){var b=!!window.opera||0<=navigator.userAgent.indexOf(" OPR/"),a=!!window.chrome&&!b;if(void 0!==window.InstallTrigger)return!0;if(!a)return!1;navigator.appVersion;var c,d=navigator.userAgent,f=""+parseFloat(navigator.appVersion),b=parseInt(navigator.appVersion,10);return a&&(c=d.indexOf("Chrome"),f=d.substring(c+7)),-1!==(c=f.indexOf(";"))&&(f=f.substring(0,c)),-1!==(c=f.indexOf(" "))&&(f=f.substring(0,c)),b=parseInt(""+f,10),isNaN(b)&&(parseFloat(navigator.appVersion),
b=parseInt(navigator.appVersion,10)),49<=b}
function MediaRecorderWrapper(b){var a,c=this;this.start=function(d,f){var k;this.timeSlice=d||5E3;c.mimeType||(c.mimeType="video/webm");-1===c.mimeType.indexOf("audio")||b.getVideoTracks().length&&b.getAudioTracks().length&&(navigator.mozGetUserMedia?(k=new MediaStream).addTrack(b.getAudioTracks()[0]):k=new MediaStream(b.getAudioTracks()),b=k);-1!==c.mimeType.indexOf("audio")&&(c.mimeType=IsChrome?"audio/webm":"audio/ogg");c.dontFireOnDataAvailableEvent=!1;k={mimeType:c.mimeType};c.disableLogs||
f||console.log("Passing following params over MediaRecorder API.",k);a=a&&null;IsChrome&&!isMediaRecorderCompatible()&&(k="video/vp8");try{a=new MediaRecorder(b,k)}catch(g){a=new MediaRecorder(b)}"canRecordMimeType"in a&&!1===a.canRecordMimeType(c.mimeType)&&(c.disableLogs||console.warn("MediaRecorder API seems unable to record mimeType:",c.mimeType));!0===c.ignoreMutedMedia&&(a.ignoreMutedMedia=!0);var h=!1;a.ondataavailable=function(b){!b.data||!b.data.size||26800>b.data.size||h||(h=!0,b=c.getNativeBlob?
b.data:new Blob([b.data],{type:c.mimeType||"video/webm"}),c.ondataavailable(b),a&&"recording"===a.state&&a.stop(),a=null,c.dontFireOnDataAvailableEvent||c.start(d,"__disableLogs"))};a.onerror=function(b){c.disableLogs||("InvalidState"===b.name?console.error("The MediaRecorder is not in a state in which the proposed operation is allowed to be executed."):"OutOfMemory"===b.name?console.error("The UA has exhaused the available memory. User agents SHOULD provide as much additional information as possible in the message attribute."):
"IllegalStreamModification"===b.name?console.error("A modification to the stream has occurred that makes it impossible to continue recording. An example would be the addition of a Track while recording is occurring. User agents SHOULD provide as much additional information as possible in the message attribute."):"OtherRecordingError"===b.name?console.error("Used for an fatal error other than those listed above. User agents SHOULD provide as much additional information as possible in the message attribute."):
"GenericError"===b.name?console.error("The UA cannot provide the codec or recording option that has been requested.",b):console.error("MediaRecorder Error",b));a&&"inactive"!==a.state&&"stopped"!==a.state&&a.stop()};try{a.start(36E5)}catch(g){a=null}setTimeout(function(){a&&"recording"===a.state&&a.requestData()},d)};this.stop=function(b){a&&"recording"===a.state&&(a.requestData(),setTimeout(function(){c.dontFireOnDataAvailableEvent=!0;a&&"recording"===a.state&&a.stop();a=null;c.onstop()},2E3))};
this.pause=function(){a&&("recording"===a.state&&a.pause(),this.dontFireOnDataAvailableEvent=!0)};this.ondataavailable=function(a){console.log("recorded-blob",a)};this.resume=function(){if(this.dontFireOnDataAvailableEvent){this.dontFireOnDataAvailableEvent=!1;var b=c.disableLogs;return c.disableLogs=!0,this.start(this.timeslice||5E3),void(c.disableLogs=b)}a&&"paused"===a.state&&a.resume()};this.clearRecordedData=function(){a&&(this.pause(),this.dontFireOnDataAvailableEvent=!0,this.stop())};this.onstop=
function(){};(function f(){a&&(!1!==function(){if("active"in b){if(!b.active)return!1}else if("ended"in b&&b.ended)return!1;return!0}()?setTimeout(f,1E3):c.stop())})()}
function StereoAudioRecorder(b){var a,c;this.start=function(d){d=d||1E3;(a=new StereoAudioRecorderHelper(b,this)).record();c=setInterval(function(){a.requestData()},d)};this.stop=function(){a&&(a.stop(),clearTimeout(c),this.onstop())};this.pause=function(){a&&a.pause()};this.resume=function(){a&&a.resume()};this.ondataavailable=function(){};this.onstop=function(){}}
function StereoAudioRecorderHelper(b,a){function c(a,b){b=new Float32Array(b);for(var c=0,d=a.length,e=0;e<d;e++){var f=a[e];b.set(f,c);c+=f.length}return b}function d(a,b,c){for(var d=c.length,e=0;e<d;e++)a.setUint8(b+e,c.charCodeAt(e))}ObjectStore.AudioContextConstructor||(ObjectStore.AudioContextConstructor=new ObjectStore.AudioContext);var f=ObjectStore.AudioContextConstructor.sampleRate,k=[],h=[],g=!1,l=0,e=a.sampleRate||f,q=-1<(a.mimeType||"audio/wav").indexOf("audio/pcm"),r=a.audioChannels||
2;this.record=function(){g=!0;l=k.length=h.length=0};this.requestData=function(){if(!u)if(0!==l){p=!0;var b=k.slice(0),f=h.slice(0),g=l;k.length=h.length=[];l=0;p=!1;var n=b=c(b,g);if(2===r&&(n=function(a,b){for(var c=a.length+b.length,d=new Float32Array(c),e=0,f=0;f<c;)d[f++]=a[e],d[f++]=b[e],e++;return d}(b,c(f,g))),q)return n=new Blob([function(a){for(var b=a.length,c=new Int16Array(b);b--;)c[b]=65535*a[b];return c.buffer}(n)],{type:"audio/pcm"}),console.debug("audio recorded blob size:",bytesToSize(n.size)),
void a.ondataavailable(n);g=new ArrayBuffer(44+2*n.length);b=new DataView(g);d(b,0,"RIFF");b.setUint32(4,44+2*n.length-8,!0);d(b,8,"WAVE");d(b,12,"fmt ");b.setUint32(16,16,!0);b.setUint16(20,1,!0);b.setUint16(22,r,!0);b.setUint32(24,e,!0);b.setUint32(28,e*r*2,!0);b.setUint16(32,2*r,!0);b.setUint16(34,16,!0);d(b,36,"data");b.setUint32(40,2*n.length,!0);for(var f=n.length,g=44,m=0;m<f;m++)b.setInt16(g,32767*n[m],!0),g+=2;n=new Blob([b],{type:"audio/wav"});console.debug("audio recorded blob size:",bytesToSize(n.size));
a.ondataavailable(n)}else p=!1};this.stop=function(){g=!1;this.requestData();n.disconnect();this.onstop()};var m=ObjectStore.AudioContextConstructor;ObjectStore.VolumeGainNode=m.createGain();var n,f=ObjectStore.VolumeGainNode;ObjectStore.AudioInput=m.createMediaStreamSource(b);(n=ObjectStore.AudioInput).connect(f);var t=a.bufferSize||2048;if(0===a.bufferSize&&(t=0),m.createJavaScriptNode)b=m.createJavaScriptNode(t,r,r);else{if(!m.createScriptProcessor)throw"WebAudio API has no support on this browser.";
b=m.createScriptProcessor(t,r,r)}t=b.bufferSize;console.debug("using audio buffer-size:",t);var p=!1;window.scriptprocessornode=b;1===r&&console.debug("All right-channels are skipped.");var u=!1;this.pause=function(){u=!0};this.resume=function(){u=!1};this.onstop=function(){};b.onaudioprocess=function(a){var b;!g||p||u||(b=a.inputBuffer.getChannelData(0),k.push(new Float32Array(b)),2===r&&(a=a.inputBuffer.getChannelData(1),h.push(new Float32Array(a))),l+=t)};f.connect(b);b.connect(m.destination)}
function WhammyRecorder(b){var a,c;this.start=function(d){for(var f in d=d||1E3,a=new WhammyRecorderHelper(b,this),this)"function"!=typeof this[f]&&(a[f]=this[f]);a.record();c=setInterval(function(){a.requestData()},d)};this.stop=function(){a&&(a.stop(),clearTimeout(c),this.onstop())};this.onstop=function(){};this.clearOldRecordedFrames=function(){a&&a.clearOldRecordedFrames()};this.pause=function(){a&&a.pause()};this.resume=function(){a&&a.resume()};this.ondataavailable=function(){}}
function WhammyRecorderHelper(b,a){function c(){if(m)return g=(new Date).getTime(),void setTimeout(c,500);if(!k){if(d)return setTimeout(c,100);var b=(new Date).getTime()-g;if(!b)return c();g=(new Date).getTime();!r.isHTMLObject&&h.paused&&h.play();q.drawImage(h,0,0,e.width,e.height);k||l.frames.push({duration:b,image:e.toDataURL("image/webp")});if(!(b=f)){var t=l.frames[l.frames.length-1],p=document.createElement("canvas");p.width=e.width;p.height=e.height;var b=p.getContext("2d"),u=Math.sqrt(Math.pow(255,
2)+Math.pow(255,2)+Math.pow(255,2)),p=new Image;p.src=t.image;b.drawImage(p,0,0,e.width,e.height);for(var t=b.getImageData(0,0,e.width,e.height),p=0,w=t.data.length,b=t.data.length/4,v=0;v<w;v+=4)Math.sqrt(Math.pow(+t.data[v],2)+Math.pow(+t.data[v+1],2)+Math.pow(+t.data[v+2],2))<=0*u&&p++;b=!(b-p<=0*b)}b||(f=!0,a.onStartedDrawingNonBlankFrames());setTimeout(c,10)}}this.record=function(d){this.width||(this.width=320);this.height||(this.height=240);this.video&&this.video instanceof HTMLVideoElement&&
(this.width||(this.width=h.videoWidth||h.clientWidth||320),this.height||(this.height=h.videoHeight||h.clientHeight||240));this.video||(this.video={width:this.width,height:this.height});this.canvas&&this.canvas.width&&this.canvas.height||(this.canvas={width:this.width,height:this.height});e.width=this.canvas.width;e.height=this.canvas.height;this.video&&this.video instanceof HTMLVideoElement?(this.isHTMLObject=!0,h=this.video.cloneNode()):((h=document.createElement("video")).src=URL.createObjectURL(b),
h.width=this.video.width,h.height=this.video.height);h.muted=!0;h.play();g=(new Date).getTime();l=new Whammy.Video(a.speed,a.quality);console.log("canvas resolutions",e.width,"*",e.height);console.log("video width/height",h.width||e.width,"*",h.height||e.height);c()};var d=!(this.clearOldRecordedFrames=function(){l.frames=[]}),f=!(this.requestData=function(){var b;m||(d=(l.frames.length&&(d=!0,b=l.frames.slice(0),l.frames=function(a){var b=document.createElement("canvas");b.width=e.width;b.height=
e.height;for(var b=b.getContext("2d"),c=[],d=a.length,f=Math.sqrt(Math.pow(255,2)+Math.pow(255,2)+Math.pow(255,2)),g=!1,h=0;h<d;h++){if(!g){var k=new Image;k.src=a[h].image;b.drawImage(k,0,0,e.width,e.height);for(var m=b.getImageData(0,0,e.width,e.height),l=0,q=m.data.length,k=m.data.length/4,n=0;n<q;n+=4)Math.sqrt(Math.pow(+m.data[n],2)+Math.pow(+m.data[n+1],2)+Math.pow(+m.data[n+2],2))<=0*f&&l++}!g&&k-l<=0*k||(g=!0,c.push(a[h]))}return 0>=(c=c.concat(a.slice(d))).length&&c.push(a[a.length-1]),c}(b),
l.compile(function(b){a.ondataavailable(b);console.debug("video recorded blob size:",bytesToSize(b.size))}),l.frames=[]),!1))}),k=!1;this.stop=function(){k=!0;this.requestData();this.onstop()};var h,g,l,e=document.createElement("canvas"),q=e.getContext("2d"),r=this,m=!1;this.pause=function(){m=!0};this.resume=function(){m=!1};this.onstop=function(){}}
function GifRecorder(b){function a(){Date.now();var a=new Blob([new Uint8Array(l.stream().bin)],{type:"image/gif"});d.ondataavailable(a);l.stream().bin=[]}if("undefined"==typeof GIFEncoder)throw"Please link: https://cdn.webrtc-experiment.com/gif-recorder.js";this.start=function(b){b=b||1E3;var d=this.videoWidth||320,n=this.videoHeight||240;f.width=h.width=d;f.height=h.height=n;(l=new GIFEncoder).setRepeat(0);l.setDelay(this.frameRate||this.speed||200);l.setQuality(this.quality||1);l.start();Date.now();
q=requestAnimationFrame(function p(a){c?setTimeout(p,500,a):(q=requestAnimationFrame(p),90>a-g||(h.paused&&h.play(),k.drawImage(h,0,0,d,n),l.addFrame(k),g=a))});e=setTimeout(a,b)};this.stop=function(){q&&(cancelAnimationFrame(q),clearTimeout(e),a(),this.onstop())};var c=!(this.onstop=function(){});this.pause=function(){c=!0};this.resume=function(){c=!1};this.ondataavailable=function(){};this.onstop=function(){};var d=this,f=document.createElement("canvas"),k=f.getContext("2d"),h=document.createElement("video");
h.muted=!0;h.autoplay=!0;h.src=URL.createObjectURL(b);h.play();var g,l,e,q=null}void 0!==MediaStreamRecorder&&(MediaStreamRecorder.MediaRecorderWrapper=MediaRecorderWrapper);void 0!==MediaStreamRecorder&&(MediaStreamRecorder.StereoAudioRecorder=StereoAudioRecorder);void 0!==MediaStreamRecorder&&(MediaStreamRecorder.StereoAudioRecorderHelper=StereoAudioRecorderHelper);void 0!==MediaStreamRecorder&&(MediaStreamRecorder.WhammyRecorder=WhammyRecorder);
void 0!==MediaStreamRecorder&&(MediaStreamRecorder.WhammyRecorderHelper=WhammyRecorderHelper);void 0!==MediaStreamRecorder&&(MediaStreamRecorder.GifRecorder=GifRecorder);
var Whammy=function(){function b(a,b){this.frames=[];this.duration=1E3/(a||1);this.quality=b||.8}function a(a){function b(a){var b=[];a=(a.length%8?Array(9-a.length%8).join("0"):"")+a;for(var c=0;c<a.length;c+=8)b.push(parseInt(a.substr(c,8),2));return new Uint8Array(b)}a=new function(a){var c=function(a){if(a[0]){for(var b=a[0].width,c=a[0].height,d=a[0].duration,e=1;e<a.length;e++)d+=a[e].duration;return{duration:d,width:b,height:c}}postMessage({error:"Something went wrong. Maybe WebP format is not supported in the current browser."})}(a);
if(!c)return[];for(var d,c=[{id:440786851,data:[{data:1,id:17030},{data:1,id:17143},{data:4,id:17138},{data:8,id:17139},{data:"webm",id:17026},{data:2,id:17031},{data:2,id:17029}]},{id:408125543,data:[{id:357149030,data:[{data:1E6,id:2807729},{data:"whammy",id:19840},{data:"whammy",id:22337},{data:(d=c.duration,[].slice.call(new Uint8Array((new Float64Array([d])).buffer),0).map(function(a){return String.fromCharCode(a)}).reverse().join("")),id:17545}]},{id:374648427,data:[{id:174,data:[{data:1,id:215},
{data:1,id:29637},{data:0,id:156},{data:"und",id:2274716},{data:"V_VP8",id:134},{data:"VP8",id:2459272},{data:1,id:131},{id:224,data:[{data:c.width,id:176},{data:c.height,id:186}]}]}]}]}],f=d=0;d<a.length;){for(var l=[],e=0;l.push(a[d]),e+=a[d].duration,++d<a.length&&3E4>e;);l={id:524531317,data:function(a,b,c){return[{data:a,id:231}].concat(c.map(function(a){var c=function(a){var b=0;if(a.keyframe&&(b|=128),a.invisible&&(b|=8),a.lacing&&(b|=a.lacing<<1),a.discardable&&(b|=1),127<a.trackNum)throw"TrackNumber \x3e 127 not supported";
return[128|a.trackNum,a.timecode>>8,255&a.timecode,b].map(function(a){return String.fromCharCode(a)}).join("")+a.frame}({discardable:0,frame:a.data.slice(4),invisible:0,keyframe:1,lacing:0,trackNum:1,timecode:Math.round(b)});return b+=a.duration,{data:c,id:163}}))}(f,0,l)};c[1].data.push(l);f+=e}return function r(a){for(var c=[],d=0;d<a.length;d++){var e=a[d].data;"object"==typeof e&&(e=r(e));"number"==typeof e&&(e=b(e.toString(2)));"string"==typeof e&&(e=new Uint8Array(e.split("").map(function(a){return a.charCodeAt(0)})));
var f=e.size||e.byteLength||e.length,g=Math.ceil(Math.ceil(Math.log(f)/Math.log(2))/8),f=f.toString(2),f=Array(7*g+8-f.length).join("0")+f,f=Array(g).join("0")+"1"+f;c.push(function(a){for(var b=[];0<a;)b.push(255&a),a>>=8;return new Uint8Array(b.reverse())}(a[d].id));c.push(b(f));c.push(e)}return new Blob(c,{type:"video/webm"})}(c)}(a.map(function(a){var b=function(a){for(var b=a.RIFF[0].WEBP[0],c=b.indexOf("�?*"),d=0,f=[];4>d;d++)f[d]=b.charCodeAt(c+3+d);return{width:16383&(f[1]<<8|f[0]),height:16383&
(f[3]<<8|f[2]),data:b,riff:a}}(function g(a){for(var b=0,c={};b<a.length;){var d=a.substr(b,4),f=parseInt(a.substr(b+4,4).split("").map(function(a){return a=a.charCodeAt(0).toString(2),Array(8-a.length+1).join("0")+a}).join(""),2),k=a.substr(b+4+4,f),b=b+(8+f);c[d]=c[d]||[];"RIFF"===d||"LIST"===d?c[d].push(g(k)):c[d].push(k)}return c}(atob(a.image.slice(23))));return b.duration=a.duration,b}));postMessage(a)}return b.prototype.add=function(a,b){if("canvas"in a&&(a=a.canvas),"toDataURL"in a&&(a=a.toDataURL("image/webp",
this.quality)),!/^data:image\/webp;base64,/gi.test(a))throw"Input must be formatted properly as a base64 encoded DataURI of type image/webp";this.frames.push({image:a,duration:b||this.duration})},b.prototype.compile=function(b){var c,f;c=(c=a,f=URL.createObjectURL(new Blob([c.toString(),"this.onmessage \x3d  function (e) {"+c.name+"(e.data);}"],{type:"application/javascript"})),c=new Worker(f),URL.revokeObjectURL(f),c);c.onmessage=function(a){a.data.error?console.error(a.data.error):b(a.data)};c.postMessage(this.frames)},
{Video:b}}();void 0!==MediaStreamRecorder&&(MediaStreamRecorder.Whammy=Whammy);window.ConcatenateBlobs=function(b,a,c){var d=[],f=0;!function h(){if(!b[f])return function(){var b=0;d.forEach(function(a){b+=a.byteLength});var e=new Uint16Array(b),f=0;d.forEach(function(a){var b=a.byteLength;0!=b%2&&(a=a.slice(0,b-1));e.set(new Uint16Array(a),f);f+=b});var g=new Blob([e.buffer],{type:a});c(g)}(),0;var g=new FileReader;g.onload=function(a){d.push(a.target.result);f++;h()};g.readAsArrayBuffer(b[f])}()};
"undefined"!=typeof module&&(module.exports=MediaStreamRecorder);"function"==typeof define&&define.amd&&define("MediaStreamRecorder",[],function(){return MediaStreamRecorder});